<script lang="ts">
	import FeaturePage from '$lib/components/remote/FeaturePage.svelte'
	import type { FEATURE } from '$lib/constants'

	const header: { title: FEATURE; subtitle: string } = {
		title: 'Forwards',
		subtitle: 'Monitor all your income generated by routing payments.'
	}

	const overview = [
		'This feature is designed for individuals and businesses operating routing nodes. It allows you to review all of your forwards, including those that were unsuccessful.',
		'The primary objective of this dashboard is to provide valuable insights that can guide routing strategies.',
		'For instance, a node operator may observe a high number of failed forwards associated with a specific channel on one of their nodes over the past month. Following further investigation, they might consider reallocating their capital within the Lightning network.'
	]

	const features = [
		{
			title: 'Filter / Sort Options',
			description: 'Status, wallet, date, fee and more'
		}
	]

	const comingSoon = null
</script>

<FeaturePage {header} {overview} {features} {comingSoon} />
