<script lang="ts">
	import FeaturePage from '$lib/components/FeaturePage.svelte'

	const header = {
		title: 'Forwards',
		subtitle: 'Monitor all your income generated by routing payments.'
	}

	const overview = [
		'This feature is geared for the routing node runners out there',
		'Browse all of your forwards, including the ones that failed to complete.',
		'This dashboard will be super useful to help surface insights that could inform your strategies to increase routing.',
		'As an example. You notice that for the last month you have had a lot of failed forwards associated with a specific channel on one of your nodes. After some investigation, you might want to consider allocating your capital to elsewhere on the Lightning network.'
	]

	const features = [
		{
			title: 'tbd',
			description: 'bla'
		},
		{
			title: 'Filter / Sort Options',
			description: 'Date, type, fee amount and more'
		}
	]

	const comingSoon = [
		{
			title: 'Charts to visualize forwards'
		},
		{
			title: 'Alerts'
		}
	]
</script>

<FeaturePage {header} {overview} {features} {comingSoon} />
